image: docker:26.1.1

variables:
    PROJECT_NAME: 'capstone-2025'
    IMAGE_NAME: 'ccr.itim.vn/product-backend/$PROJECT_NAME'
    DEFECTDOJO_PRODUCT_TYPENAME: 'product-backend'
    SAST_EXCLUDED_ANALYZERS: 'spotbugs,nodejs-scan,security-code-scan,gosec,pmd-apex,flawfinder,bandit,brakeman,eslint'

include:
    - template: Security/SAST.gitlab-ci.yml
    - remote: 'https://git.itim.vn/public-repos/gitlab-ci-templates/-/raw/main/sast/upload_to_dedo.yml'
    - remote: 'https://git.itim.vn/public-repos/gitlab-ci-templates/-/raw/main/sast/custom_config.yml'

stages:
    - test
    - sast-report
    - build
    - deploy

build_dev:
    stage: build
    services:
        - docker:26.1.1-dind
    only:
        - /^[0-9]+\.[0-9]+\.[0-9]+\-dev$/
    except:
        - branches
        - triggers
    script:
        - docker build -t $IMAGE_NAME:$CI_COMMIT_TAG -f ./server/Dockerfile ./server
        - docker push $IMAGE_NAME:$CI_COMMIT_TAG
        - echo "Pushed image $IMAGE_NAME:$CI_COMMIT_TAG"

deploy_dev:
    stage: deploy
    id_tokens:
        ID_TOKEN:
            aud: kubernetes
    image: ccr.itim.vn/admins/cicd-scripts:latest
    only:
        - /^[0-9]+\.[0-9]+\.[0-9]+\-dev$/
    variables:
        SERVICE_NAME: ${PROJECT_NAME}        # your service name, as defined in k8s manifest
        NAMESPACE: product-backend-dev                # namespace, with -prod or -dev suffix
        OVERLAYS: dev                      # overlays in k8s-manifest
        IMAGES: $IMAGE_NAME:$CI_COMMIT_TAG       # allow multiple images, separate by commas (,). Please make sure using the right image tag or your service will crash
        ID_TOKEN: $ID_TOKEN
        CI_COMMIT_MESSAGE: $CI_COMMIT_MESSAGE
    script:
        - /script/deploy.py

build_prod:
    stage: build
    services:
        - docker:26.1.1-dind
    only:
        - /^[0-9]+\.[0-9]+\.[0-9]+$/
    except:
        - branches
        - triggers
    script:
        - docker build -t $IMAGE_NAME:$CI_COMMIT_TAG -f ./server/Dockerfile ./server
        - docker push $IMAGE_NAME:$CI_COMMIT_TAG
        - echo "Pushed image $IMAGE_NAME:$CI_COMMIT_TAG"

deploy_prod:
    stage: deploy
    id_tokens:
        ID_TOKEN:
            aud: kubernetes
    image: ccr.itim.vn/admins/cicd-scripts:latest
    only:
        - /^[0-9]+\.[0-9]+\.[0-9]+$/
    variables:
        SERVICE_NAME: ${PROJECT_NAME}        # your service name, as defined in k8s manifest
        NAMESPACE: product-backend-prod                # namespace, with -prod or -dev suffix
        OVERLAYS: prod                      # overlays in k8s-manifest
        IMAGES: $IMAGE_NAME:$CI_COMMIT_TAG       # allow multiple images, separate by commas (,). Please make sure using the right image tag or your service will crash
        ID_TOKEN: $ID_TOKEN
        CI_COMMIT_MESSAGE: $CI_COMMIT_MESSAGE
    script:
        - /script/deploy.py
