version: "3"

services:
  app:
    container_name: ${APP_NAME}-app
    build:
      context: ./server
      dockerfile: Dockerfile
    #            target: builder
    #        command: pnpm preview
    volumes:
      - ./server:/app
    ports:
      - ${APP_PORT}:3000
    networks:
      - default
    env_file:
      - .env
      - ./server/.env
    depends_on:
      - redis-cluster
  #        command: ["sleep", "10000"]

  nginx:
    image: nginx:latest
    container_name: ${APP_NAME}-nginx
    depends_on:
      - app
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/data/cache:/data/nginx/cache
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    networks:
      - default

  redis-cluster:
    container_name: ${APP_NAME}-redis
    image: redis:latest
    ports:
      - "6379"
    networks:
      - default
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
