global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"] # 👈 use service/container name, not localhost

  # Your app (cocbot-api)
  - job_name: "cocbot-api"
    static_configs:
      - targets: ["app:3000"] # 👈 service name from docker-compose.yml
    metrics_path: "/metrics"
    scrape_interval: 10s
    scrape_timeout: 5s
    scheme: http

  # Node exporter
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"] # 👈 matches service name in monitoring compose
    scrape_interval: 15s
